name: build and push docker image

on:
  workflow_call:

    inputs:
      environment: 
        type: string
        required: false
      image_name:
        required: true
        type: string
      version: 
        type: string
        required: true
      dockerfile: 
        type: string
        required: true
      dockerargs:
        type: string
        description: "Additional build arguments for docker, provided as a multiline string"
        required: false
    secrets: 
      azure_client_id: 
        required: true
      azure_tenant_id: 
        required: true
      azure_subscription_id: 
        required: true
      registry: 
        required: true
      app_id:
        required: false
      private_key: 
        required: false
      mdu_pat:
        required: true
      prefix:
        required: true

    outputs:
      image_name:
        description: "image-name"
        value: ${{ jobs.build-push-image.outputs.image_name }}
      image_version:
        description: "image-version"
        value: ${{ jobs.build-push-image.outputs.image_version }}

jobs:
  build-push-image:
    permissions:
      id-token: write # This is required for requesting the OIDC JWT
      contents: read  # This is required for actions/checkout
      packages: read

    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    outputs:
      image_name: ${{ steps.set-outputs.outputs.image_name }}
      image_version: ${{ steps.set-outputs.outputs.image_version }}
    steps:
      - uses: actions/checkout@v2      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker # defaults to "docker-containerized"      
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.azure_client_id }}
          tenant-id: ${{ secrets.azure_tenant_id }}
          subscription-id: ${{ secrets.azure_subscription_id }}

      - name: Log in to Azure ACR
        run: -|
          az acr login -n ${{secrets.registry}}

      - name: Authorize Github app
        id: generate_token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.app_id }}
          private_key: ${{ secrets.private_key }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: | 
            ${{ secrets.registry }}/${{ secrets.prefix }}${{inputs.image_name}}:${{inputs.version}}
            ${{ secrets.registry }}/${{ secrets.prefix }}${{inputs.image_name}}:latest
          file: ${{ inputs.dockerfile }}
          build-args: |
            NPM_TOKEN=${{ secrets.mdu_pat }}
            ${{inputs.dockerargs}}
      - name: Set Outputs
        id: set-outputs
        run: |
          $image_name_mask = "${{ secrets.prefix }}${{inputs.image_name}}"
          echo "::add-mask::$image_name_mask"
          echo "::set-output name=image_name::$image_name_mask"
          echo "::set-output name=image_version::${{inputs.version}}"


