name: build_image_from_main
on:
  pull_request_review:
    types: [submitted,edited]
  workflow_call:
    inputs:
      image_name:
        required: true

      repository:
        required: true
        type: string
        default: ${{ github.event.repository.name }}

jobs:
  deploy-production:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: approved
        run: echo "This PR was approved"

      - name: checkout
        uses: actions/checkout@v2
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker # defaults to "docker-containerized"
      
      - name: Log in to Azure ACR
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_APPID }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/${{env.API_NAME}}:1.0.${{github.run_number}}
          file: Dockerfile

  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
    
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker # defaults to "docker-containerized"

      - name: Log in to Azure ACR
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_APPID }}
          password: ${{ secrets.ACR_PASSWORD }}

        - name: Build and push container image to registry
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: ${{ secrets.ACR_REGISTRY }}/test-${{inputs.image_name}}:1.0.${{github.run_number}}
            file: Dockerfile
