name: build and push docker image
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      repository:
        required: true
        type: string
      version: 
        type: string
        required: true
      dockerfile: 
        type: string
        required: true
    secrets: 
      azure_client_id: 
        required: true
      azure_tenant_id: 
        required: true
      azure_subscription_id: 
        required: true
      registry: 
        required: true
jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker # defaults to "docker-containerized"      

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.azure_client_id }}
          tenant-id: ${{ secrets.azure_tenant_id }}
          subscription-id: ${{ secrets.azure_subscription_id }}

      - name: Log in to Azure ACR
        run: -|
          az acr login -n ${{inputs.registry}}


      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ inputs.registry }}/test-${{inputs.image_name}}:${{inputs.version}}
          file: ${{ inputs.dockerfile }}

  deploy-production:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: approved
        run: echo "This PR was approved"
      - uses: actions/checkout@v2      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker # defaults to "docker-containerized"      
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.azure_client_id }}
          tenant-id: ${{ secrets.azure_tenant_id }}
          subscription-id: ${{ secrets.azure_subscription_id }}

      - name: Log in to Azure ACR
        run: -|
          az acr login -n ${{secrets.registry}}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.registry }}/${{env.API_NAME}}:${{inputs.version}}
          file: ${{ inputs.dockerfile }}

