name: build and push docker image

env:
  IMAGE_PREFIX: "test"

on:
  workflow_call:

    inputs:
      image_name:
        required: true
        type: string
      version: 
        type: string
        required: true
      dockerfile: 
        type: string
        required: true
    secrets: 
      azure_client_id: 
        required: true
      azure_tenant_id: 
        required: true
      azure_subscription_id: 
        required: true
      registry: 
        required: true
    outputs:
      image_name:
        description: "Image-name"
        value: ${{ jobs.build-push-image.outputs.image_name }}
      image_version:
        description: "Image-version"
        value: ${{ jobs.build-push-image.outputs.image_version }}

jobs:
  determine-build:    
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: "echo environment"
        run: |
          echo setting environment to production
        env:
          IMAGE_PREFIX: ""


  build-push-image:
    permissions:
      id-token: write # This is required for requesting the OIDC JWT
      contents: read  # This is required for actions/checkout
    
    runs-on: ubuntu-latest
    needs: determine-build
    outputs:
      image_name: ${{ steps.set-outputs.outputs.image_name }}
      image_version: ${{ steps.set-outputs.outputs.image_version }}
    steps:
      - name: approved
        run: echo "This PR was approved"
      - uses: actions/checkout@v2      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker # defaults to "docker-containerized"      
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.azure_client_id }}
          tenant-id: ${{ secrets.azure_tenant_id }}
          subscription-id: ${{ secrets.azure_subscription_id }}

      - name: Log in to Azure ACR
        run: -|
          az acr login -n ${{secrets.registry}}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: | 
            ${{ secrets.registry }}/${{ env.IMAGE_PREFIX }}${{inputs.image_name}}:${{inputs.version}}
            ${{ secrets.registry }}/	${{ env.IMAGE_PREFIX }}${{inputs.image_name}}:latest
          file: ${{ inputs.dockerfile }}
      - name: Set Outputs
        id: set-outputs
        run: |
          echo "::set-output name=image_name::${{ env.IMAGE_PREFIX }}${{inputs.image_name}}"
          echo "::set-output name=image_version::${{inputs.version}}"


