name: Build and deploy BFF

on:
  workflow_call:
    inputs:     
      release_name:
        type: string
        required: true
        description: "helm release name"
      image_name:
        type: string
        required: true
        description: "image name"
      
      image_version:
        type: string
        required: true
        description: "image version/tag"

      helm_chart_name:
        type: string
        default: planday-integrations
        required: false
        description: helm chart to use for installation
      env_variables:
        type: string
        description: "environment variales for the format: --set=key1=value1 --set=key2=value2"
        required: false
      environment:
        description: 'Environment to deploy to'
        type: string
        required: true
    secrets:
      dns_name:
        required: true
      azure_client_id:
        required: true
      azure_tenant_id:
        required: true 
      azure_subscription_id:
        required: true
      azure_acr_registry:
        required: true
      cluster_name:
        required: true
      cluster_resource_group:
        required: true
      env_secrets:
        required: false



jobs:
  deploy:    
    environment: ${{inputs.environment}}
    permissions:
      id-token: write # This is required for requesting the OIDC JWT      
    runs-on: 'ubuntu-latest'
    steps:      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker # defaults to "docker-containerized"      

    - name: Install azure cli
      run: |
        which az || { curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash ; }

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.azure_client_id }}
        tenant-id: ${{ secrets.azure_tenant_id }}
        subscription-id: ${{ secrets.azure_subscription_id }}
        
    - name: Log in to Azure ACR
      run: |
        az acr login -n ${{secrets.azure_acr_registry}}
    
    - name: 'Add helm repository'
      run: |
        helm repo add acr_registry ${{secrets.azure_acr_registry}}
        helm repo update
        helm repo ls


    - name: Login-k8s
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.cluster_name }}
        cluster-name: ${{ secrets.cluster_resource_group }}
        admin: 'true'

    - name: 'Deploy'
      run: |
        namespace=$(echo ${{inputs.environment}} | tr "[:upper:]" "[:lower:]")
        registry=$(echo ${{secrets.azure_acr_registry}} | sed 's/.azurecr.io//g' )
        dnsname=$(echo ${{secrets.dns_name}} | tr "[:upper:]" "[:lower:]")
        echo $namespace
        echo $dnsname
        echo $registry
        echo ${{inputs.env_variables}}
 

        { kubectl create ns $namespace && kubectl label namespace $namespace istio-injection=enabled; } || echo "namespace exists, continuing"
        
        helm upgrade ${{inputs.release_name}} --install --namespace=$namespace --set network.dnsName=$dnsname --set image.tag=${{inputs.image_version}} --set image.repository=${{ secrets.azure_acr_registry }} --set image.name=${{inputs.image_name}} $registry/${{inputs.helm_chart_name}} --create-namespace ${{inputs.env_variables}} ${{secrets.env_secrets}} 
