name: Build and deploy BFF

on:
  workflow_call:
    inputs:     
      environment:
        description: 'Environment to deploy to'
        type: string
        required: true

      release_name:
        type: string
        required: true
        description: "helm release name"

      image_name:
        type: string
        required: true
        description: "image name"
      
      image_version:
        type: string
        required: true
        description: "image version/tag"

      helm_chart_name:
        type: string
        default: planday-integrations
        required: false
        description: helm chart to use for installation
    secrets:
      azure_client_id:
        required: true
      azure_tenant_id:
        required: true 
      azure_subscription_id:
        required: true
      azure_acr_registry:
        required: true
      cluster_name:
        required: true
      cluster_resource_group:
        required: true


jobs:
  deploy:    
    permissions:
      id-token: write # This is required for requesting the OIDC JWT      
    runs-on: 'ubuntu-latest'
    steps:      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker # defaults to "docker-containerized"      

    - name: Install azure cli
      run: |
        which az || { curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash ; }

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.azure_client_id }}
        tenant-id: ${{ secrets.azure_tenant_id }}
        subscription-id: ${{ secrets.azure_subscription_id }}

#    - uses: azure/setup-helm@v3
#      with:
#        version: 'v3.10.0' # default is latest (stable)
#      id: install
        
    - name: Log in to Azure ACR
      run: |
        az acr login -n ${{secrets.azure_acr_registry}}
    
    - name: 'Add helm repository'
      run: |
        az acr helm repo add --name ${{secrets.azure_acr_registry}}
        helm repo update
        helm repo ls


    - name: Login-k8s
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.cluster_name }}
        cluster-name: ${{ secrets.cluster_resource_group }}
        admin: 'true'

    - name: 'Deploy'
      run: |
        namespace=$(echo ${{inputs.environment}} | tr "[:upper:]" "[:lower:]")
        registry=$(echo ${{secrets.azure_acr_registry}} | sed 's/.azurecr.io//g' )
        echo $namespace
        echo $registry
        
        helm upgrade ${{inputs.release_name}} --install --namespace=$namespace --set image.tag=${{inputs.image_version}} --set image.name=${{inputs.image_name}} $registry/${{inputs.helm_chart_name}} --create-namespace